### ISSUE TITLE
[FEAT]: Typescript Support

### ISSUE THREAD

**Issue by jcrapuchettes** [getlago/lago-nodejs-client#67]
As we are using this package in our typescript project, it would be nice to have types defined so that we don't have to check if the shape of the objects change with each release.

**Comment by ansmonjol** [comment]
Hello @jcrapuchettes, thanks for your comment.

We do have a client repo that uses Typescript: https://github.com/getlago/lago-javascript-client
Switching to it would solve your type definition needs :) 

Probably _lago-notejs-client_ repo should be deprecated, as the TS repo would work for non-typescript projects.
Also because it seems misleading and costly to have 2 JS repo.

I'll plan to make it as deprecated very soon.

How does it sounds?

**Comment by jcrapuchettes** [comment]
That sounds great. We will switch to that repo. Thank you.
